admin:
  username: sba
  password: sba12358
spring:
  config.import: optional:configserver:http://${admin.username}:${admin.password}@localhost:8888/config
  application.name: demo
  profiles.active: development
